---
- name: Create Nextcloud Database
  community.postgresql.postgresql_db:
    name: nextcloud
    owner: nextcloud_user
    state: present
  become: yes
  become_user: postgres

- name: Create vb-manager-prd Database
  community.postgresql.postgresql_db:
    name: vb_manager_prd
    owner: vb_manager_user
    state: present
  become: yes
  become_user: postgres