---
# --- Swap config
swap_file_path: "/swapfile"
swap_size_gb: "2"

# Versioning
postgres_version: "17"
postgres_package: "postgresql17-server"

# Storage
storage_disks:
  data:
    dev: "/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_PGDATA01"
    path: "/var/lib/pgsql"
  backup:
    dev: "/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_PGBACKUP01"
    path: "/mnt/backups"

# group_vars or host_vars
pg_hba_host_rules:
  - databases: nextcloud
    users: nextcloud_user
    source: 10.0.1.204/32
  - databases: vb_manager_prd
    users: vb_manager_user
    source: 10.0.1.203/32
  - databases: all
    users: deploy_user
    source: 10.0.1.11/32

# RBAC Strategy - Tier A (Groups/Roles)
pg_rbac_groups:
  - { name: "db_admin_grp", flags: "NOLOGIN,CREATEDB,CREATEROLE" }
  - { name: "app_rw_grp", flags: "NOLOGIN" }

# RBAC Strategy - Tier B (Login Users)
pg_rbac_users:
  - name: "deploy_user"
    password: "{{ vault_deploy_user_password }}"
  - name: "nextcloud_user"
    password: "{{ vault_nextcloud_password }}"
  - name: "vb_manager_user"
    password: "{{ vault_vb_manager_password }}"

pg_rbac_memberships:
  - { user: "deploy_user", group: "db_admin_grp" }
  - { user: "deploy_user", group: "app_rw_grp" }
  - { user: "nextcloud_user", group: "app_rw_grp" }
  - { user: "vb_manager_user", group: "app_rw_grp" }
  - { user: "deploy_user", group: "vb_manager_user" }

# Network
homelab_subnet: "10.0.1.0/24"

# Clients allowed to pass firewalld
trusted_clients:
  - { ip: "10.0.1.11/32", comment: "ASUS-TUF-2021" }
  - { ip: "10.0.1.203/32", comment: "app-server" }
  - { ip: "10.0.1.204/32", comment: "file-server" }

# pgBackRest Configuration
stanza_name: "demo"

# SMB Config
smb_server_ip: 10.0.1.248
smb_share_name: HOMELAB-NAS
smb_username: HOMELAB-NAS
# smb_domain: is optional, defaults to WORKGROUP

# API Section
api_repo_url: "git@github.com:yourusername/vb-manager-api.git"
api_deploy_path: "/opt/vb-manager-api"
api_db_name: "vb_manager_prd"
api_db_user: "vb_manager_user"
github_deploy_token: "{{ vault_github_deploy_token }}"
api_trusted_clients:
  - { ip: "10.0.1.203/32", comment: "app-server (Streamlit)" }
  - { ip: "10.0.1.11/32",  comment: "ASUS-TUF-2021 (dev)" }
nextcloud_base_url: "http://10.0.1.204:8080/remote.php/dav/files/vb-manager/"
nextcloud_user: "vb-manager"
nextcloud_password: "{{ vault_nextcloud_password }}"