# --- Swap config
swap_file_path: "/swapfile"
swap_size_gb: "2"

# --- WD Home Cloud Duo Details
smb_share: "//10.0.1.248/HOMELAB-NAS/nextcloud"
mount_path: "/mnt/wd_cloud"
smb_user: "HOMELAB-NAS"
# smb_pass: "@vault"

# --- Nexcloud Service Config
nextcloud_fqdn: "nextcloud.example.com" # Adjust this for your NPM setup later
# vault_redis_password: "@vault"
npm_ip: "10.0.1.2"


# --- DB environment ---
pg_host: "10.0.1.201" # Put your DB server IP here
pg_db_name: "nextcloud"
pg_db_user: "nextcloud_user"
# vault_nextcloud_password: "@vault" 
