# Hardcoded prefix based on the `ls -l /dev/disk/by-id/` output, variable serial
disk_serial: "APPDATA01"
data_disk_path: "/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_{{ disk_serial }}"

# Git Repo and Deployment destination
repo_url: "https://oauth2:{{ vault_github_token }}@github.com/jpeixe72/VB_TeamManager.git"
dest_dir: "/home/ubuntu/Projects/vb-manager"

# Database settings
db_host: "192.168.1.201"
db_port: "5432"
db_name: "vb_manager_prd"
db_user: "vb_manager_user"

# Streamlit VM reaching db-server-01 via LAN
api_base_url: "http://192.168.1.201:8000"